# Generated by Django 4.2.17 on 2025-01-04 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AutoParts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brands',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='model',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='part',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='paymenthistory',
            options={'managed': False},
        ),
    ]
